name: mocktail

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.12-dev
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: pub get
      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed .
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Run tests
        run: dart test --coverage=coverage && pub run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
